// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEnJuFbRjX7aEaDbS1uhKhfuFlj1CmroY',
    appId: '1:586811051172:web:f0dfa479462776c941aa31',
    messagingSenderId: '586811051172',
    projectId: 'edulink-98008',
    authDomain: 'edulink-98008.firebaseapp.com',
    storageBucket: 'edulink-98008.firebasestorage.app',
    measurementId: 'G-S36HJWSWLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrSUGvKkBK45KezIq3zpE30fj68WffheM',
    appId: '1:586811051172:android:dce7e76bebe0bf3141aa31',
    messagingSenderId: '586811051172',
    projectId: 'edulink-98008',
    storageBucket: 'edulink-98008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1wx4MaLRmpUXvrIrMgAFsUeDy7BFETk',
    appId: '1:586811051172:ios:ce4e81c419294c8541aa31',
    messagingSenderId: '586811051172',
    projectId: 'edulink-98008',
    storageBucket: 'edulink-98008.firebasestorage.app',
    iosBundleId: 'com.example.edulink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1wx4MaLRmpUXvrIrMgAFsUeDy7BFETk',
    appId: '1:586811051172:ios:ce4e81c419294c8541aa31',
    messagingSenderId: '586811051172',
    projectId: 'edulink-98008',
    storageBucket: 'edulink-98008.firebasestorage.app',
    iosBundleId: 'com.example.edulink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEnJuFbRjX7aEaDbS1uhKhfuFlj1CmroY',
    appId: '1:586811051172:web:b9e9ae1bca08a1f541aa31',
    messagingSenderId: '586811051172',
    projectId: 'edulink-98008',
    authDomain: 'edulink-98008.firebaseapp.com',
    storageBucket: 'edulink-98008.firebasestorage.app',
    measurementId: 'G-HKWGCDFDVK',
  );

}